### ISSUE TITLE
[REQUEST] ~ Github Actions CI

### ISSUE THREAD

**Issue by BD103** [ReplAPI-it/ReplAPI.it-Python#11]
Add continuous integration with Github Actions. Currently, this is a low priority because of the following:

- This project uses [Poetry](https://github.com/python-poetry/poetry) for dependency management
- Github Actions does not initially support Poetry
- [Installing Poetry works](https://github.com/snok/install-poetry), but commands are not registered
  - For instance, even though it installed Isort, the `isort` command isn't available
  - This makes it very difficult to use all the dependencies necessary for the project

**Comment by darkdarcool** [comment]
hmmm, so I don't feel useless, I found this:
https://github.com/marketplace/actions/python-poetry-action?version=v2.1.0
maybe it will work?

**Comment by JBYT27** [comment]
@darkdarcool, seems like that might work :)

**Comment by darkdarcool** [comment]
yah ok. Hey, like you said yesterday, can you invite me to the react app your making?

**Comment by JBYT27** [comment]
lol, sure, sorry

**Comment by darkdarcool** [comment]
@BD103, you can use pip, because it has the same packages as poetry, and i would assume github has it installed, or you can run a bash file in the actions that will do it for you

**Comment by BD103** [comment]
Actually, I'm developing a solution for that. See [BD103/Ballad](https://github.com/BD103/Ballad).

**Comment by RayhanADev** [comment]
> Actually, I'm developing a solution for that. See [BD103/Ballad](https://github.com/BD103/Ballad).

Ballad looks dope ngl 😎

**Comment by darkdarcool** [comment]
@RayhanADev, yea it does, good work @BD103!

**Comment by darkdarcool** [comment]
Also the name is super cool

**Comment by BD103** [comment]
Haha thanks!

**Comment by JBYT27** [comment]
lol yep

**Comment by BD103** [comment]
Adding with #15

**Comment by darkdarcool** [comment]
Is this issue relevant now that we are about the merge a pull request for this?

**Comment by BD103** [comment]
Fixed

**Comment by darkdarcool** [comment]
:)
