### ISSUE TITLE
Design User and Post Classes

### ISSUE THREAD

**Issue by BD103** [ReplAPI-it/ReplAPI.it-Python#12]
Currently, we need to support two classes:

- User
- Post

I have laid down the framework for these, but they do not actually do anything.
Remember, **this package should work exactly as [ReplAPI-it-NodeJS](https://github.com/ReplAPI-it/ReplAPI.it-NodeJS), ideas for features should be implemented there first, then ported.**

**Comment by JBYT27** [comment]
Got it, btw @BD103, should I pull on repl? So it replicates github code?

**Comment by BD103** [comment]
Yes
