### ISSUE TITLE
Flat Style on Badge

### ISSUE THREAD

**Issue by RayhanADev** [ReplAPI-it/ReplAPI.it-Python#16]
Is it possible to make the Ballad Badge a `for-the-badge` style to match up with the other badges?

**Comment by JBYT27** [comment]
@BD103, do you think this is possible? Thanks!

**Comment by BD103** [comment]
I'm making a commit now

**Comment by BD103** [comment]
Fixed with ed8dcb13702ddacc969bb3380e2494e351feadc4, closing.

**Comment by RayhanADev** [comment]
Neat :)
