### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by darkdarcool** [ReplAPI-it/ReplAPI.it-Python#18]
# Docs
So, I noticed that we don't have any docs, even an MD set up for how to use the module, and it's really bugging me, so, I was wondering if we could get a doc website set up with vercel, or even an MD ready for when it's time to write the docs.

This is just a request, thanks!

**Comment by RayhanADev** [comment]
Wellll there technically is no module. That’s the thing, once ya’ll actually have something to document docs can be a worry.

**Comment by darkdarcool** [comment]
ik, if you read it again, it says to get it started, not to actually start saying the exact way on how to use it.

**Comment by BD103** [comment]
Yes, we are not documenting yet. Even so, I do not want to use Vercel or any sort of Nodejs program. If we are going to host the docs, we are going to use a Python static site generator (which I will be looking into).
