### ISSUE TITLE
i am confuzzled

### ISSUE THREAD

**Issue by iop3** [ReplAPI-it/ReplAPI.it-Python#19]
What's the difference between the REPLAPI.it-Python and the REPLAPI?

**Comment by iop3** [comment]
if you think this question is stupid then just close it and tell me that my iq < 0

**Comment by iop3** [comment]
mass ping party: @RayhanADev @JBYT27 @BD103 @darkdarcool

**Comment by darkdarcool** [comment]
your iq < 0

**Comment by JBYT27** [comment]
Uh, please don't mass ping. And they are just 2 different api's made by different and same ppl. Also with diff syntax

**Comment by iop3** [comment]
alright thanks @darkdarcool for the fact. Also @JBYT27 i didn't mean to mass ping i did it to speed up the process cuz when i asked a issue once in some guy's profile that guy like took 1 week to answer me. And when i pinged him it only took 1 hour for him to answer so yeah jb but ill try not to mass ping again.

**Comment by iop3** [comment]
Ok thanks @JBYT27

**Comment by RayhanADev** [comment]
@iop3 From the developer guidelines (but should be applied anywhere)

> I'd like to add that in addition issues on this repository (or any repo in general lol) should not be used to make comments or ask questions, especially if its for help or about another commit/issue/pr.
> 
> If you have a question/comment about a Commit, make a comment on the commit itself or open a discussion.
> If you have a question/comment about an Issue, make a comment on the same issue or open a discussion.
> If you have a question/comment about a pull request, make a comment on the pull request or the commit that merges it in.
> If you just generally need help, use the threads on the Repl.

**Comment by darkdarcool** [comment]
@RayhanADev, can you open the discussion tab for this repo, as the Developer Guidelines says you can use?

**Comment by RayhanADev** [comment]
@darkdarcool done! Not sure why it was close though...

**Comment by darkdarcool** [comment]
me neither! I read the comment and my brain went `hol' up`
