### ISSUE TITLE
[BUG] ~ staging.replit.com/graphql doesn't support requests

### ISSUE THREAD

**Issue by BD103** [ReplAPI-it/ReplAPI.it-Python#20]
**Describe the bug**
Making a standard request on [staging.replit.com](https://staging.replit.com) just returns the URL [https://replit.slack.com/archives/C3AA56MFS/p1622838662154800](https://replit.slack.com/archives/C3AA56MFS/p1622838662154800).

**To Reproduce**

**Expected behavior**
Running `CLASS.collect()` returns a dictionary of the data, while running `CLASS.collect_raw()` returns JSON.

**Screenshots**
![Screenshot 2021-06-08 08 38 45](https://user-images.githubusercontent.com/59022059/121187505-1faaab80-c836-11eb-984a-2f27ed6eb361.png)

**Desktop (please complete the following information):**
 - OS: ChromeOS
 - Browser: Chrome
 - Version: Not sure

**Additional context**
This also breaks `CLASS.collect()`, because it cannot convert text to a dictionary.

**Comment by JBYT27** [comment]
Hmm, is there any way to fix this without tinkering with staging.replit.com?

**Comment by BD103** [comment]
No clue. Does anyone have a slack account?

**Comment by JBYT27** [comment]
Huh. Personally, I don't. Maybe ask Ray?

**Comment by RayhanADev** [comment]
@BD103 I do have a Slack account but I'm not in the Replit workspace :(. The solution is to make it use the `https://replit.com/graphql` endpoint. The Java lib is able to use it and I can curl that endpoint but I can't do it from the NodeJS package using node-fetch... LMK how it goes with Python requests :).

**Comment by BD103** [comment]
Ah. If Turbio says to do it, then I'll switch over to regular.

**Comment by JBYT27** [comment]
Nice.

**Comment by darkdarcool** [comment]
There seems to be an error with black in the ballad lint action

**Comment by JBYT27** [comment]
Yeah, @BD103 said they would fix it.

**Comment by BD103** [comment]
For now, we are going to have to ignore the Black lint error. I've been working hard on Ballad, but I'm really busy the next few weeks.

**Comment by darkdarcool** [comment]
ah, ok.

**Comment by BD103** [comment]
Tested and (kinda) fixed with 57a39094bbdc42027a60a4e95471b0647e16694e

**Comment by RayhanADev** [comment]
> Tested and (kinda) fixed with [57a3909](https://github.com/ReplAPI-it/ReplAPI.it-Python/commit/57a39094bbdc42027a60a4e95471b0647e16694e)

Yay glad you're back! What do you mean by "kinda" I'm curious.

**Comment by darkdarcool** [comment]
Yea me too

**Comment by BD103** [comment]
Requesting at the URL worked fine. That commit just fixes another error that would mess up collecting data.

So the commit is basically unrelated but makes testing work better.

**Comment by darkdarcool** [comment]
Ah ok

**Comment by darkdarcool** [comment]
I can work in about 30 min
