### ISSUE TITLE
[BUG] ~ Github to Replit sync

### ISSUE THREAD

**Issue by JBYT27** [ReplAPI-it/ReplAPI.it-Python#21]
**Github to Replit sync broken**
I checked out our team repl for the python module, and tried both pulling and pushing.
However, as this does happen, the sync has broke.
I already left a message inside the repl, but I'm leaving an issue as well. You might want to import this GitHub repo in Replit.
> Just letting you know

**To Reproduce**
1. Go to 'Version Control'
2. Click on 'Pull'
3. Click on 'Push' this time

**Expected behavior**
It's supposed to pull for you and push for you as it's synced, but it doesn't. It reacts like a null (lol).

**Screenshots**
Check the repl for more.

**Desktop (please complete the following information):**
 - OS: ChromeOS
 - Browser: Chrome
 - Version: 91.0.4472.81 (i think)

**Comment by RayhanADev** [comment]
Yeah that happens sometimes :(. Check if there's any differences between the Repl and the Repo, make the changes in the Repo, and then delete the Repl (so many Rep-s xD) and clone it to the team again.

**Comment by JBYT27** [comment]
:( got it, ill try that. (Haha yes xD) Yeah, ok

**Comment by BD103** [comment]
Just saw this now. I'd recommend just creating your own personal Repl, then editing it there. Then you can manage the code and delete if necessary.

**Comment by JBYT27** [comment]
Ah, ok. Thanks!
