### ISSUE TITLE
Upgrade to an HTTPS package

### ISSUE THREAD

**Issue by RayhanADev** [ReplAPI-it/ReplAPI.it-Python#22]
Previously when fetching the staging domain you could use HTTP requests (i.e. what the [`requests`](https://pypi.org/project/requests/) package uses) however when fetching the standard domain **that is no longer the case**. You need to use an HTTPS package. I would experiment with [`urllib`](https://github.com/urllib3/urllib3), although I'm not sure if it supports https. Worst case scenario if nothing works you can use the native Python HTTPS APIs, make your own package (you only need GET and POST requests) and use that (it's what I did for the NodeJS package).

**Comment by JBYT27** [comment]
Huh. Got it, thanks!

**Comment by BD103** [comment]
Requests can support both HTTP and HTTPS. It is a wrapper for urllib. Plus, it should request the right protocol.

https://github.com/ReplAPI-it/ReplAPI.it-Python/blob/master/replapi_it/classes/config.py#L4

**Comment by RayhanADev** [comment]
@BD103 nice! Just wanted to make sure :).
