### ISSUE TITLE
[REQUEST] ~ Documentation needed

### ISSUE THREAD

**Issue by Isaiah-Day** [ReplAPI-it/ReplAPI.it-Python#26]
This looks like a cool project, but you seem to be lacking a documentation? I would recomend having it in the README file, and you should make sure it also goes on Pypi to.

**Comment by darkdarcool** [comment]
Since summer, the project has slowed down, and there’s no one to develop the docs, and the package isn’t developed enough to the point where we would need that

**Comment by Isaiah-Day** [comment]
ok! thanks! where is the code for the package? i can start writing the docs for what you have so far! @darkdarcool

**Comment by rayhanadev** [comment]
> ok! thanks! where is the code for the package? i can start writing the docs for what you have so far! @darkdarcool

Actually this is the repo for all the available code lol.

**Comment by darkdarcool** [comment]
And I don’t think we need that right now, but I’ll make sure to call you back when we do start developing it!
