### ISSUE TITLE
Repository Meta

### ISSUE THREAD

**Issue by RayhanADev** [ReplAPI-it/ReplAPI.it-Python#3]
New contributors typically look to a CONTRIBUTING.md and CODE_OF_CONDUCT.md for how to contribute to a repository. Also be sure to specify a Commit Convention (or lack of one) so that commit history is clean. Lastly, if Python has a code linter and/or formatter you should include the setup for these and configuration files so that all your code remains clean and consistent.

Speaking from experience I ran a repository for 3 months without the above and trying to make changes or consistency was a pain. Adopting these best practices will help you run this module smoothly!

**Comment by RayhanADev** [comment]
Oops I accidentally linked the previous PR and closed the issue too soon.

Resolved: Code of Conduct
In Progress: Contributing

@JBYT27 @BD103 since this is your project it would be preferable if you wrote this up, but if you want to use the one on the NodeJs package as template that's fine too.

**Comment by JBYT27** [comment]
Got it!

**Comment by BD103** [comment]
I'll work on it tomorrow.

**Comment by darkdarcool** [comment]
Quick question, I’m guessing this is a pip module, but with the new files and folders, I’m not sure it will work with pip?

**Comment by RayhanADev** [comment]
@darkdarcool I'm not very experienced with creating Python Modules so I just flew through a tutorial and scrapped this together. My plan is to hopefully get BD103 and JBYT27 to work on this when the get a chance so I'm trying to speed up the startup process.

**Comment by darkdarcool** [comment]
Ah ok, yea I saw the repl, there would be a couple things I would changes

**Comment by BD103** [comment]
I believe this is fixed, closing.

**Comment by JBYT27** [comment]
Nice
