### ISSUE TITLE
Setup a Project Board

### ISSUE THREAD

**Issue by RayhanADev** [ReplAPI-it/ReplAPI.it-Python#4]
You may want to setup a Kanban board in Projects to track issues and deadlines for your first release of the module. It might help keep things organized when transpiling the NodeJS package to a Python Module.

**Comment by JBYT27** [comment]
Hmm, okie! Thanks! :)

**Comment by darkdarcool** [comment]
when are you guys gonna work on this?

**Comment by JBYT27** [comment]
@darkdarcool - Not exactly sure, but probably sometime when we're free and we can work on this, or after the first replapi.it module (js)

**Comment by RayhanADev** [comment]
Finished Project Board
