### ISSUE TITLE
Interesting!

### ISSUE THREAD

**Issue by darkdarcool** [ReplAPI-it/ReplAPI.it-Python#9]
Hey! I was just wondering @BD103, since I know python ~~and have no ideas~~, can I join this proj?

If no, that's fine, I'll just leave a couple pull requests here and there

Thanks!

**Comment by BD103** [comment]
Maybe, but I'm not going to invite anyone else until #7 is done

**Comment by darkdarcool** [comment]
Okieeed

**Comment by darkdarcool** [comment]
Also @BD103, it looks like it’s merged already?

**Comment by BD103** [comment]
Yea, just give me one more day.

**Comment by darkdarcool** [comment]
ah ok

**Comment by darkdarcool** [comment]
hi, sorry to bother, but it is the next day. Is it possible for me to join? Or should I wait and or leave some pull requests

**Comment by BD103** [comment]
@darkdarcool I invited you to the repo with write access. Feel free to created new branches and PRs, though ask me or @JBYT27 before editing the master branch. Thanks for helping!

**Comment by darkdarcool** [comment]
k cool. Also is it possible to make edits to the repl so I don't accidentally break GitHub?

**Comment by BD103** [comment]
I just clone the repo and edit it from there. I don't bother with the shared Repl, as there are too many people on it.

**Comment by darkdarcool** [comment]
ok lol, can I inv you to there because the live chat would help me develop

**Comment by darkdarcool** [comment]
Wait, I'll leave what I do in pull requests, and you guys can do whatever you want to them

**Comment by darkdarcool** [comment]
ah ok.
